enabled = true
rpc_method = "dinner.build"

to = "telegram"
destination_group = "-1002918707721"
destination_topic = "201"
destination_language = "ru"

generate_image = true
render_template = "ğŸ‘©â€ğŸ³ What's for Dinner?\n\n{summary}"

max_prep_time_minutes = 20
max_cook_time_minutes = 45
exclude_ingredients = ["pork", "shrimp"]
cuisine = "Mediterranean, Italian, simple European, Turkish, Belarus"
other = "Kid-friendly, not too spicy, healthy, can be cooked in one pan if possible"