enabled = true
to = "telegram"
# Ğ£ĞºĞ°Ğ¶Ğ¸Ñ‚Ğµ ÑĞ²Ğ¾Ğ¸ destination Ğ¸ destination_topic
destination = "-1002918707721" 
destination_topic = "774" 
destination_language = "ru"
render_template = "ğŸ‡ºğŸ‡¦ Ukraine News Digest ({section})\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "news_ua"

[feeds]
general = [
    "https://www.pravda.com.ua/rss/",
    "https://rss.rbc.ua/ukr/newsline.rss",
    "https://www.unian.ua/rss_all.rss",
    "https://nv.ua/rss/all.xml"
]