enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "201"
destination_language = "ru"
render_template = "ğŸ‘©â€ğŸ³ What's for Dinner?\n\n{summary}"
generate_image = true

cuisine = "Mediterranean, Italian, simple European, Turkish, Belarus"
exclude_ingredients = ["pork", "shrimp"]
max_prep_time_minutes = 20
max_cook_time_minutes = 45
other = "Kid-friendly, not too spicy, healthy, can be cooked in one pan if possible"